# Development Dockerfile
FROM node:18-alpine

WORKDIR /app

# Install dependencies only when package.json changes
COPY package*.json ./
RUN npm install

# Add node_modules/.bin to PATH
ENV PATH /app/node_modules/.bin:$PATH

# Start development server with host 0.0.0.0 to allow external connections
ENV HOST=0.0.0.0
EXPOSE 3000

CMD ["npm", "start"]